### ISSUE TITLE
File "/usr/local/share/pmga-3.0.2/pmga.py", line 1421, in create_json

### ISSUE THREAD

**Issue by ybdong919** [rpetit3/pmga#1]
Traceback (most recent call last):
  File "/usr/local/share/pmga-3.0.2/pmga.py", line 1640, in <module>
    mash_results = obtain_species(args.fasta, args.threads)
  File "/usr/local/share/pmga-3.0.2/pmga.py", line 1471, in obtain_species
    return create_json(mash_results, thresholds)
  File "/usr/local/share/pmga-3.0.2/pmga.py", line 1421, in create_json
    mash_hit = data[lab_id]["mash_results"]["Top Match"]
KeyError: 'Top Match'

**Comment by ybdong919** [comment]
In this issue, the input contigs file in fasta format can go through in the script.
